[www]
host = "127.0.0.1"
port = 8080

[backend]
base_url = "http://127.0.0.1:8765"
request_timeout_seconds = 10.0

[session]
cookie_name = "shellrpg_session"

[integration]
wiki_base_url = "https://wiki.shellrpg.tld"

[assets]
asset_proxy_route = "/asset"
asset_primary_base_url = "https://cdn.jsdelivr.net/gh/RPG-Wulf/ShellRPG-cdn@main/assets/www"
asset_fallback_base_urls = ["https://cdn-shellrpg.dns.army/assets/www"]
asset_origin_candidates_path = "./var/asset-origins.toml"
asset_request_timeout_seconds = 1.2
